package main.java;
/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'hp' at '4/7/15 10:53 AM' with Gradle 2.4
 *
 * @author hp, @date 4/7/15 10:53 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
